---
# subl tasks

# install sublime
- name: check if sublime is installed
  command: subl -v
  register: subl_exists
  ignore_errors: True

- name: download sublime
  when: subl_exists|failed
  get_url: url={{ subl_install_url }} dest=/tmp/subl.dmg mode=0440

- name: Mount sublime image
  when: subl_exists|failed
  command: hdiutil attach /tmp/subl.dmg

- name: Copy sublime app to Applications directory
  when: subl_exists|failed
  copy: src="/Volumes/Sublime Text/Sublime Text.app" dest=/Applications

- name: Unmount sublime image
  when: subl_exists|failed
  command: hdiutil detach /Volumes/Sublime\ Text

# subl command
- name: Change subl perms
  file: path="/Applications/Sublime Text.app/Contents/SharedSupport/bin/subl" mode=775
  sudo: yes

- name: Subl command symlink
  when: subl_exists|failed
  file: src="/Applications/Sublime Text.app/Contents/SharedSupport/bin/subl" dest=/usr/local/bin/subl state=link

# install package control
- name: download package control
  when: subl_exists|failed
  get_url: url={{ package_control_url }} dest="/tmp/Package Control.sublime-package" mode=0440

- name: Copy package control to installed packages
  when: subl_exists|failed
  copy: src="/tmp/Package Control.sublime-package" dest="{{ subl_app_folder }}/Installed Packages"

# default packages
- name: SublimeLinter3
  git: repo="https://github.com/SublimeLinter/SublimeLinter3.git" dest="{{ subl_app_folder }}Packages/SublimeLinter" update=yes
  tags:
    - subl-packages
